apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: iqgroper/ml_prod_hw:latest
      name: fastapi-ml
      ports:
        - containerPort: 8000
      readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 3